---
# tasks file for jupyter-notebook

# 1/3 Copy Dockerfile

# 2/3 Build docker image

# 3/3 Launch docker container
- name: launch jupyterhub container
  docker:
    name: '{{ jhub_notebook_docker_container }}'
    image: '{{ jhub_notebook_docker_image }}'
    state: reloaded
    restart_policy: always
